import {Inter} from 'next/font/google'

import StyledComponentsRegistry from '../components/utility/StyledComponentsRegistry'
import { InterUnitProvider } from '@/components/utility/InterUnitProvider'

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
<InterUnitProvider>
        {children}
</InterUnitProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
