name: Formatter

on:
  workflow_call:

jobs:
    formatter:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - name: Run Formatter (Prettier)
              run: bun run format
