name: Install Dependencies

on:
    workflow_call:

jobs:
    install-dependencies:
        name: Install Dependencies
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: |
                  ./node_modules
                  **/node_modules
                key: node_modules-${{ hashFiles('bun.lockb') }}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: bun install
