name: Linter

on:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    linter:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - name: Change NodeJS to verison from package.json
              uses: actions/setup-node@v3
              with:
                node-version-file: 'package.json'
            - name: Install Dependencies
              run: yarn
            - name: Run ESLint
              run: yarn lint
