name: Native Unit Testing

on:
    pull_request:
    push:
      branches:
        - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    native-unit-testing:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: macos-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - name: Change NodeJS to verison from package.json
              uses: actions/setup-node@v3
              with:
                node-version-file: 'package.json'
            - name: Install Dependencies
              run: yarn
            - name: Build Packages
              run: yarn build:packages
            - name: Run Native Unit Tests
              run: yarn test:unit --selectProjects native
              env:
                TEST_ENV_NAME: native
