name: PR Checks

on:
  pull_request:


jobs:
    pr-checks:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Change NodeJS to verison from package.json
              uses: actions/setup-node@v3
              with:
                node-version-file: 'package.json'
            - name: Install Dependencies
              run: bun install
    formatter:
        uses: ./.github/workflows/formatter.yml
    linter:
        uses: ./.github/workflows/linter.yml
    unit-testing:
        uses: ./.github/workflows/unit-testing.yml
