name: PR Checks

on:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true


jobs:
    pr-checks:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Change NodeJS to verison from package.json
              uses: actions/setup-node@v3
              with:
                node-version-file: 'package.json'
            - name: Install Dependencies
              run: bun install
            - name: Formatter
              uses: ./.github/workflows/formatter.yml
            - name: Linter
              uses: ./.github/workflows/linter.yml
            - name: Unit Testing
              uses: ./.github/workflows/unit-testing.yml
