name: PR Checks

on:
  pull_request:


jobs:
    setup:
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Change NodeJS to verison from package.json
              uses: actions/setup-node@v3
              with:
                node-version-file: 'package.json'
            - name: Cache Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                name: ./node_modules
                key: node_modules-${{ hashFiles('bun.lockb') }}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: bun install
    formatter:
        needs: setup
        uses: ./.github/workflows/formatter.yml
    linter:
        needs: setup
        uses: ./.github/workflows/linter.yml
    unit-testing:
        needs: setup
        uses: ./.github/workflows/unit-testing.yml
