name: Unit Testing

on:
    workflow_call:
    push:
      branches:
        - main

jobs:
    setup-unit-tests:
        name: Setup Unit Tests
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip-ci') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Cache Dependencies
              id: dependencies-cache
              uses: actions/cache@v3
              with:
                path: |
                  ./node_modules
                  **/node_modules
                key: node_modules-${{ hashFiles('bun.lockb') }}
            - name: Cache Build
              id: build-package-ci-cache
              uses: actions/cache@v3
              with:
                path: |
                  **/dist
                key: build:package:ci
            - name: Install Dependencies
              if: steps.dependencies-cache.outputs.cache-hit != 'true'
              run: bun install
            - name: Build Packages
              run: bun run build:package:ci
    native-unit-tests:
         name: Native Unit Tests
         runs-on: ubuntu-latest
         needs: setup-unit-tests
         steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Cache Dependencies
              id: dependencies-cache
              uses: actions/cache@v3
              with:
                path: |
                  ./node_modules
                  **/node_modules
                key: node_modules-${{ hashFiles('bun.lockb') }}
            - name: Cache Build
              id: build-package-ci-cache
              uses: actions/cache@v3
              with:
                path: |
                  **/dist
                key: build:package:ci
            - name: Install Dependencies
              if: steps.dependencies-cache.outputs.cache-hit != 'true'
              run: bun install
            - name: Build Packages
              if: steps.build-package-ci-cache.outputs.cache-hit != 'true'
              run: bun run build:package:ci
            - name: Run Native Unit Tests
              run: bun run test:unit --selectProjects native --coverageDirectory ./coverage/native
              env:
                TEST_ENV_NAME: native
            - name: Upload Test Coverage
              uses: actions/upload-artifact@v3
              with:
                name: native-coverage-reports
                path: |
                  **/coverage/native
    web-unit-tests:
        name: Web Unit Tests
        runs-on: ubuntu-latest
        needs: setup-unit-tests
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - name: Cache Dependencies
              id: dependencies-cache
              uses: actions/cache@v3
              with:
                path: |
                  ./node_modules
                  **/node_modules
                key: node_modules-${{ hashFiles('bun.lockb') }}
            - name: Cache Build
              id: build-package-ci-cache
              uses: actions/cache@v3
              with:
                path: |
                  **/dist
                key: build:package:ci
            - name: Install Dependencies
              if: steps.dependencies-cache.outputs.cache-hit != 'true'
              run: bun install
            - name: Build Packages
              if: steps.build-package-ci-cache.outputs.cache-hit != 'true'
              run: bun run build:package:ci
            - name: Setup Chromedriver
              uses: nanasess/setup-chromedriver@v2
            - name: Start Chromedriver
              run: |
                  export DISPLAY=:99
                  chromedriver --url-base=/wd/hub &
                  sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
            - name: Run Web Unit Tests
              run: bun run test:unit --selectProjects web --coverageDirectory ./coverage/web
              env:
                TEST_ENV_NAME: web
            - name: Upload Test Coverage
              uses: actions/upload-artifact@v3
              with:
                name: web-coverage-reports
                path: |
                  **/coverage/web
    report:
        name: Report Test Coverage
        runs-on: ubuntu-latest
        needs: [web-unit-tests, native-unit-tests]
        steps:
            - name: Checkout Latest
              uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - uses: actions/download-artifact@v3
              with:
                name: web-coverage-reports
                path: |
                  **/coverage/web
            - uses: actions/download-artifact@v3
              with:
                name: native-coverage-reports
                path: |
                  **/coverage/native
            - name: Merge Coverage Reports
              run: bun run test:unit:coverage-merge
            - name: Generate Coverage Report
              run: bun run test:unit:coverage-report
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


