name: Unit Testing

on:
    workflow_call:
    push:
      branches:
        - main

jobs:
    native-unit-tests:
      name: Native Unit Testing
      uses: ./.github/workflows/native-unit-testing.yml
    web-unit-tests:
      name: Web Unit Testing
      uses: ./.github/workflows/web-unit-testing.yml
    report-test-coverage:
      name: Report Test Coverage
      needs: [native-unit-tests, web-unit-tests]
      uses: ./.github/workflows/report-test-coverage.yml
